### ISSUE TITLE
Calculate Tax Rate doesn't expose any errors

### ISSUE THREAD

**Issue by equinoxmatt** [quaderno/quaderno-php#19]
Occasionally the QuadernoTaxRate::calculate() method returns false.  However I don't see a way to retrieve that error, and the Quaderno console doesn't appear to show any logs and shed any light on why the API call failed.

My proposal would be to add an optional callback parameter to the method to allow the consumer to do something upon failure. In my case log the error.

I am happy to submit a PR, but I wanted to check:

1) Is there a way to retrieve the error that I have missed?
2) If my proposal is something that would likely be accepted and if you welcome pull requests.

For context, the method in question:

```
  public static function calculate($params) {
    $return = false;
    $response = QuadernoBase::apiCall('GET', 'tax_rates', 'calculate', $params);

    if (QuadernoBase::responseIsValid($response))
      $return = new self($response['data']);

    return $return;
  }
  ```

https://github.com/quaderno/quaderno-php/blob/0350c795af2be61cf69cbb8f7f6af55de163527f/quaderno_tax_rate.php#L15

**Comment by xxswingxx** [comment]
> Is there a way to retrieve the error that I have missed?

No, you're right. Quaderno-php only returns false when the request cannot be processed (either due to a timeout, an external service not responding in time or rate limits hit)

> If my proposal is something that would likely be accepted and if you welcome pull requests.

We'll glady accept a PR that makes the usage of this library easier. However in order to keep consistency across the rest of the classes, given the fact that errors are usually returned in the "errors" attribute for other classes (https://github.com/quaderno/quaderno-php/issues/18#issuecomment-954711718), what do you think about making it optional to return an array including that field?

Something like this:

```php
$display_errors = true
$tax = QuadernoTaxRate::calculate($params, $display_errors); // $display_errors should be optional to prevent a breaking change in this release, false by default
$tax->errors;

/* array(
  "response_code" =>503,
   ...
)
*/
```

**Comment by equinoxmatt** [comment]
@xxswingxx  - thanks for the response.

I prefer the callback solution, but I understand the need for  consistency, so I will submit a PR with the solution you recommend.
