### ISSUE TITLE
PHP 8.x support?

### ISSUE THREAD

**Issue by equinoxmatt** [quaderno/quaderno-php#21]
Hello,

Do you officially support PHP 8? I are running code using this library in PHP 7.4, which works fine, but I am in the process of upgrading the application to PHP 8.1.

During testing, I have only found one issue so far:

https://www.php.net/releases/8.1/en.php#deprecations_and_bc_breaks

The QuadernoClass::jsonSerialize() throws a deprecated error. PHP internal functions now have return types, so the fix is simple:

```
	/**
     * Specify data which should be serialized to JSON.
     *
     * @return array
     */
    public function jsonSerialize(): mixed
    {
        return $this->data;
    }
```

My core question is, will there be an official release to make this library compatible with PHP 8?

I am happy to submit PRs for this particular issue, but I don't use all the elements of this library, just the tax.

**Comment by xxswingxx** [comment]
Hi @equinoxmatt , I'm afraid we don't support PHP 8.1 yet and we don't plan to do it in the short term given it's adoption rate is still not high enough.

**Comment by equinoxmatt** [comment]
Thanks, appreciate the response :)

**Comment by VincentLanglet** [comment]
> Hi @equinoxmatt , I'm afraid we don't support PHP 8.1 yet and we don't plan to do it in the short term given it's adoption rate is still not high enough.

Can you reconsider this now that PHP 8.1 is the oldest PHP version with active support ?
https://www.php.net/supported-versions.php

**Comment by polimorfico** [comment]
@VincentLanglet The current version already works with PHP 8.2. Can you please check it out? Let us know if you find any issues. Happy to help!

**Comment by VincentLanglet** [comment]
> @VincentLanglet The current version already works with PHP 8.2. Can you please check it out? Let us know if you find any issues. Happy to help!

Sure, it technically *does work* since the requirement in composer is `php >= 5.2`, with a lot of php deprecations which
- write a lot of logs
- fails stricts CI/applications
- create a feeling of insecurity when looking for using this library for a long-term company project
A good way to see this could be to add a CI running tests on different PHP versions.

Reason of the deprecation:
- Some signature need to be explicitly declared:
```
public function jsonSerialize(): mixed
```
to solve the deprecation and add support for PHP 9 in the long term or at least an attribute `#[\ReturnTypeWillChange]` need to be added to just avoid throwing lot of deprecations.

- Since PHP 8.2, dynamic properties are deprecated (https://www.php.net/manual/fr/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties) which means that properties like
https://github.com/quaderno/quaderno-php/blob/master/quaderno_model.php#L75
https://github.com/quaderno/quaderno-php/blob/master/quaderno_model.php#L107
certainly trigger deprecations too

- Since nothing is typehinted I wonder if the [Passing null to non-nullable parameters of built-in functions](https://www.php.net/manual/fr/migration81.deprecated.php#migration81.deprecated.core.null-not-nullable-internal) is not sometimes triggered

On the other side, some things can be done too to improve the usage of this library:
- Following PSR4, providing namespace when using those class
- Adding typhint or at least more phpdoc about the param and return type of all the public method ; looking at the usage of the v2 https://packagist.org/packages/quaderno/quaderno/php-stats#2, nobody is using this library with an older php version than 7 (which is btw not supported https://www.php.net/supported-versions.php). You could move the constraint to at aleast `>= 7` and enjoy the new feature (for instance typehint).

Thanks for your consideration

**Comment by polimorfico** [comment]
@VincentLanglet Thank you so much for your feedback. We're working on a new version and we'll take all your suggestions into consideration.

Please feel free to send us any PR you want us to add in that news version. Thanks!

**Comment by VincentLanglet** [comment]
> Please feel free to send us any PR you want us to add in that news version. Thanks!

I opened https://github.com/quaderno/quaderno-php/pull/22 as a first step
